// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { PrepareSenderRequest } from '../../fbs/client-to-server/prepare-sender-request.js';


export enum BodyRequest {
  NONE = 0,
  PrepareSenderRequest = 1
}

export function unionToBodyRequest(
  type: BodyRequest,
  accessor: (obj:PrepareSenderRequest) => PrepareSenderRequest|null
): PrepareSenderRequest|null {
  switch(BodyRequest[type]) {
    case 'NONE': return null; 
    case 'PrepareSenderRequest': return accessor(new PrepareSenderRequest())! as PrepareSenderRequest;
    default: return null;
  }
}

export function unionListToBodyRequest(
  type: BodyRequest, 
  accessor: (index: number, obj:PrepareSenderRequest) => PrepareSenderRequest|null, 
  index: number
): PrepareSenderRequest|null {
  switch(BodyRequest[type]) {
    case 'NONE': return null; 
    case 'PrepareSenderRequest': return accessor(index, new PrepareSenderRequest())! as PrepareSenderRequest;
    default: return null;
  }
}
