// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PrepareSenderRequest {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PrepareSenderRequest {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPrepareSenderRequest(bb:flatbuffers.ByteBuffer, obj?:PrepareSenderRequest):PrepareSenderRequest {
  return (obj || new PrepareSenderRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPrepareSenderRequest(bb:flatbuffers.ByteBuffer, obj?:PrepareSenderRequest):PrepareSenderRequest {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PrepareSenderRequest()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

roomName():string|null
roomName(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
roomName(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startPrepareSenderRequest(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRoomName(builder:flatbuffers.Builder, roomNameOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, roomNameOffset, 0);
}

static endPrepareSenderRequest(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  builder.requiredField(offset, 4) // room_name
  return offset;
}

static createPrepareSenderRequest(builder:flatbuffers.Builder, roomNameOffset:flatbuffers.Offset):flatbuffers.Offset {
  PrepareSenderRequest.startPrepareSenderRequest(builder);
  PrepareSenderRequest.addRoomName(builder, roomNameOffset);
  return PrepareSenderRequest.endPrepareSenderRequest(builder);
}
}
