// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { PrepareSenderResponse } from '../../fbs/client-to-server/prepare-sender-response.js';


export enum BodyResponse {
  NONE = 0,
  PrepareSenderResponse = 1
}

export function unionToBodyResponse(
  type: BodyResponse,
  accessor: (obj:PrepareSenderResponse) => PrepareSenderResponse|null
): PrepareSenderResponse|null {
  switch(BodyResponse[type]) {
    case 'NONE': return null; 
    case 'PrepareSenderResponse': return accessor(new PrepareSenderResponse())! as PrepareSenderResponse;
    default: return null;
  }
}

export function unionListToBodyResponse(
  type: BodyResponse, 
  accessor: (index: number, obj:PrepareSenderResponse) => PrepareSenderResponse|null, 
  index: number
): PrepareSenderResponse|null {
  switch(BodyResponse[type]) {
    case 'NONE': return null; 
    case 'PrepareSenderResponse': return accessor(index, new PrepareSenderResponse())! as PrepareSenderResponse;
    default: return null;
  }
}
